/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.frames;

import br.com.beans.Compromisso;
import br.com.beans.Usuario;
import com.sun.glass.events.KeyEvent;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.sql.*;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public Usuario user = null;
    public ArrayList<Usuario> usersList = new ArrayList<Usuario>();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        pnlLogin.setVisible(true);
        pnlCompromissos.setVisible(false);
        pnlRegistrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCompromissos = new javax.swing.JPanel();
        lblCompromissos = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCompromissos = new javax.swing.JList<>();
        btnDeslogar = new javax.swing.JButton();
        pnlRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        lblRegLogin = new javax.swing.JLabel();
        txtRegLogin = new javax.swing.JTextField();
        lblRegSenha = new javax.swing.JLabel();
        lblRegConfirmSenha = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        pwdSenha = new javax.swing.JPasswordField();
        pwdConfirmSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        lblLoginInfo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblLogin1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnRegistrarSe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pwdSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompromissos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCompromissos.setForeground(new java.awt.Color(0, 0, 0));
        lblCompromissos.setText("Compromissos");

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setText("Título");

        lblData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblData.setText("Data");

        lblLocal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocal.setText("Local");

        txtLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLocalKeyPressed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstCompromissos);

        btnDeslogar.setText("Deslogar");
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCompromissosLayout = new javax.swing.GroupLayout(pnlCompromissos);
        pnlCompromissos.setLayout(pnlCompromissosLayout);
        pnlCompromissosLayout.setHorizontalGroup(
            pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompromissosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCompromissos)
                    .addGroup(pnlCompromissosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocal)
                            .addComponent(lblData)
                            .addComponent(lblTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtLocal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompromissosLayout.createSequentialGroup()
                        .addComponent(btnDeslogar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCompromissosLayout.setVerticalGroup(
            pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompromissosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlCompromissosLayout.createSequentialGroup()
                        .addComponent(lblCompromissos)
                        .addGap(37, 37, 37)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocal)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnDeslogar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblRegistrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistrar.setText("Registrar");

        lblRegLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegLogin.setText("Login");

        lblRegSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegSenha.setText("Senha");

        lblRegConfirmSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegConfirmSenha.setText("Confirmar Senha");

        btnRegistrar.setText("Registrar-se");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        pwdConfirmSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdConfirmSenhaKeyPressed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(btnRegistrar))
                            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRegLogin)
                                    .addComponent(lblRegSenha)
                                    .addComponent(lblRegConfirmSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pwdSenha)
                                    .addComponent(txtRegLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(pwdConfirmSenha))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                        .addComponent(lblRegistrar)
                        .addGap(108, 108, 108))))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addComponent(lblRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegLogin)
                            .addComponent(txtRegLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegSenha)
                            .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRegConfirmSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLoginInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginInfo.setText("Faça seu login para acessar!");

        lblLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLogin.setText("Login");

        lblLogin1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLogin1.setText("Senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnRegistrarSe.setText("Registrar-se");
        btnRegistrarSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSeActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Não tem uma conta?");

        pwdSenhaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdSenhaLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarSe))
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEntrar)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addComponent(lblLogin1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pwdSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLoginInfo)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginInfo)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin1)
                    .addComponent(pwdSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSe)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCompromissos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCompromissos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSeActionPerformed
        pnlLogin.setVisible(false);
        pnlRegistrar.setVisible(true);
    }//GEN-LAST:event_btnRegistrarSeActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        txtLogin.setText("");
        pwdSenhaLogin.setText("");

        boolean usuarioExistente = false;
        char[] senha = pwdSenha.getPassword();
        char[] confirmaSenha = pwdConfirmSenha.getPassword();
        String senhaCompleta = "";
        String confirmSenhaCompleta = "";

        for (int i = 0; i < senha.length; i++) {
            senhaCompleta += senha[i];
        }
        for (int i = 0; i < confirmaSenha.length; i++) {
            confirmSenhaCompleta += confirmaSenha[i];
        }

        if (!txtRegLogin.getText().trim().isEmpty()
                && !senhaCompleta.trim().isEmpty()
                && !confirmSenhaCompleta.trim().isEmpty()) {
            for (int i = 0; i < usersList.size(); i++) {
                if (txtRegLogin.getText().equals(usersList.get(i).getLogin())) {
                    usuarioExistente = true;
                    i = usersList.size() + 1;
                }
            }

            if (!usuarioExistente) {
                if (senhaCompleta.equals(confirmSenhaCompleta)) {
                    JOptionPane.showMessageDialog(this, "Registrado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);

                    user = new Usuario("Matheus", 16, "Masc", txtRegLogin.getText(), senhaCompleta);
                    usersList.add(user);

                    pnlRegistrar.setVisible(false);
                    pnlLogin.setVisible(true);
                    limparCampos();

                } else {
                    JOptionPane.showMessageDialog(this, "As senhas digitadas são diferentes!", "Senhas inválidas!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Esse login já existe!", "Senhas inválidas!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Um ou mais campos estão em branco!", "Campos em branco!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        char[] senha = pwdSenhaLogin.getPassword();

        boolean usuarioExiste = false;
        String senhaCompleta = "";
        int indiceUser = -1;

        for (int i = 0; i < senha.length; i++) {
            senhaCompleta += senha[i];
        }

        if (!txtLogin.getText().trim().isEmpty() && !senhaCompleta.trim().isEmpty()) {
            for (int i = 0; i < usersList.size(); i++) {
                if (txtLogin.getText().equals(usersList.get(i).getLogin())) {
                    usuarioExiste = true;
                    indiceUser = i;
                    user = usersList.get(i);
                    i = usersList.size() + 1;
                }
            }

            if (usuarioExiste) {
                if (senhaCompleta.equals(user.getSenha())) {
                    JOptionPane.showMessageDialog(this, "Logado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                    limparCampos();
                    atualizaListaCompromissos();
                    pnlLogin.setVisible(false);
                    pnlCompromissos.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Senha incorreta!", "Senhas inválida!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado!", "Usuário inválido!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Um ou mais campos estão em branco!", "Campos em branco!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void pwdSenhaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdSenhaLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_pwdSenhaLoginKeyPressed

    private void pwdConfirmSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdConfirmSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnRegistrarActionPerformed(null);
        }
    }//GEN-LAST:event_pwdConfirmSenhaKeyPressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        pnlRegistrar.setVisible(false);
        pnlLogin.setVisible(true);
        limparCampos();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (!txtLocal.getText().trim().isEmpty()
                    && !txtTitulo.getText().trim().isEmpty()
                    && !txtData.getText().trim().isEmpty()) {
                if (txtData.getText().length() == 10) {
                    user.addCompromisso(txtLocal.getText(), txtTitulo.getText(), "Pendente", txtData.getText());

                    atualizaListaCompromissos();
                } else {
                    JOptionPane.showMessageDialog(null, "Data inválida! \nFormato: 01/02/2000", "Data inválida", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "]Erro");
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        String[] vazio = {""};
        lstCompromissos.setListData(vazio);
        pnlCompromissos.setVisible(false);
        pnlLogin.setVisible(true);
        limparCampos();
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void txtLocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvarActionPerformed(null);
        }
    }//GEN-LAST:event_txtLocalKeyPressed

    public void atualizaListaCompromissos() {
        String[] listaCompromissos = new String[user.getQntdCompromissos()];
        
        for (int i = 0; i < user.getQntdCompromissos(); i++) {
            listaCompromissos[i] = "[" + (i + 1) + "] ";
            listaCompromissos[i] += user.getCompromisso(i).getTitulo();
            listaCompromissos[i] += " - " + user.getCompromisso(i).getLocal();
            listaCompromissos[i] += " - " + user.getCompromisso(i).getData();
        }
        lstCompromissos.setListData(listaCompromissos);
        limparCampos();
    }

    public void limparCampos() {
        txtData.setText("");
        txtLocal.setText("");
        txtLogin.setText("");
        txtRegLogin.setText("");
        txtTitulo.setText("");
        pwdConfirmSenha.setText("");
        pwdSenha.setText("");
        pwdSenhaLogin.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarSe;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompromissos;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblLoginInfo;
    private javax.swing.JLabel lblRegConfirmSenha;
    private javax.swing.JLabel lblRegLogin;
    private javax.swing.JLabel lblRegSenha;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstCompromissos;
    private javax.swing.JPanel pnlCompromissos;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPasswordField pwdConfirmSenha;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JPasswordField pwdSenhaLogin;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtRegLogin;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
