/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.compromissos.frames;

import br.com.compromissos.beans.Usuario;
import br.com.compromissos.connection.ConnectionFactory;
import br.com.compromissos.dao.CompromissosDAO;
import br.com.compromissos.dao.PessoaDAO;
import br.com.compromissos.dao.UsuarioDAO;
import com.sun.glass.events.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Connection conexao = ConnectionFactory.getConnection();
    private UsuarioDAO user = new UsuarioDAO();
    private CompromissosDAO comps = new CompromissosDAO();
    private PessoaDAO pessoa = new PessoaDAO();
    private ArrayList<Usuario> usersList = new ArrayList<Usuario>();
    private String usuarioLogado = null;
    private DefaultTableModel modeloTabela = null;
    private boolean tabelaIniciada = false;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        login();
    }

    public void login() {
        this.setSize(250, 220);
        pnlLogin.setVisible(true);
        pnlCompromissos.setVisible(false);
        pnlRegistrar.setVisible(false);
        limparCampos();
    }

    public void registrar() {
        this.setSize(350, 310);
        pnlLogin.setVisible(false);
        pnlCompromissos.setVisible(false);
        pnlRegistrar.setVisible(true);
        limparCampos();
    }

    public void compromissos() {
        this.setSize(670, 330);
        pnlLogin.setVisible(false);
        pnlCompromissos.setVisible(true);
        pnlRegistrar.setVisible(false);
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCompromissos = new javax.swing.JPanel();
        lblCompromissos = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnDeslogar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblUserLogado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompromissos = new javax.swing.JTable();
        pnlRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        lblRegLogin = new javax.swing.JLabel();
        txtRegLogin = new javax.swing.JTextField();
        lblRegSenha = new javax.swing.JLabel();
        lblRegConfirmSenha = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        pwdRegSenha = new javax.swing.JPasswordField();
        pwdRegConfirmSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRegNome = new javax.swing.JTextField();
        txtRegIdade = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        pnlLogin = new javax.swing.JPanel();
        lblLoginInfo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblLogin1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnRegistrarSe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pwdSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompromissos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCompromissos.setForeground(new java.awt.Color(0, 0, 0));
        lblCompromissos.setText("Compromissos");

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setText("Título");

        lblData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblData.setText("Data");

        lblLocal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLocal.setText("Local");

        txtLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLocalKeyPressed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnDeslogar.setText("Deslogar");
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });

        jLabel5.setText("dd/MM/aaaa");

        tblCompromissos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Data", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCompromissos);

        javax.swing.GroupLayout pnlCompromissosLayout = new javax.swing.GroupLayout(pnlCompromissos);
        pnlCompromissos.setLayout(pnlCompromissosLayout);
        pnlCompromissosLayout.setHorizontalGroup(
            pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompromissosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCompromissos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompromissosLayout.createSequentialGroup()
                        .addComponent(btnDeslogar)
                        .addGap(148, 148, 148)
                        .addComponent(btnSalvar))
                    .addGroup(pnlCompromissosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocal)
                            .addComponent(lblData)
                            .addComponent(lblTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtLocal))))
                    .addComponent(lblUserLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCompromissosLayout.setVerticalGroup(
            pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompromissosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompromissosLayout.createSequentialGroup()
                        .addComponent(lblCompromissos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocal)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlCompromissosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnDeslogar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblRegistrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistrar.setText("Registrar");

        lblRegLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegLogin.setText("Login");

        lblRegSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegSenha.setText("Senha");

        lblRegConfirmSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegConfirmSenha.setText("Confirmar Senha");

        btnRegistrar.setText("Registrar-se");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        pwdRegConfirmSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdRegConfirmSenhaKeyPressed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nome Completo");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Idade");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outro", "Masc", "Femi" }));

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrar)
                .addGap(108, 108, 108))
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRegLogin)
                            .addComponent(lblRegSenha)
                            .addComponent(lblRegConfirmSenha)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pwdRegSenha)
                                .addComponent(txtRegLogin)
                                .addComponent(pwdRegConfirmSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(txtRegNome))
                            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                                .addComponent(txtRegIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtRegIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistrarLayout.createSequentialGroup()
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegLogin)
                            .addComponent(txtRegLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegSenha)
                            .addComponent(pwdRegSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdRegConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRegConfirmSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLoginInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginInfo.setText("Faça seu login para acessar!");

        lblLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLogin.setText("Login");

        lblLogin1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLogin1.setText("Senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnRegistrarSe.setText("Registrar-se");
        btnRegistrarSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSeActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Não tem uma conta?");

        pwdSenhaLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdSenhaLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarSe))
                    .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEntrar)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                            .addComponent(lblLogin1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pwdSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLoginInfo)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginInfo)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin1)
                    .addComponent(pwdSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSe)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCompromissos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCompromissos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSeActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarSeActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        boolean usuarioExistente = false;
        char[] senha = pwdRegSenha.getPassword();
        char[] confirmaSenha = pwdRegConfirmSenha.getPassword();
        String senhaCompleta = "";
        String confirmSenhaCompleta = "";

        for (int i = 0; i < senha.length; i++) {
            senhaCompleta += senha[i];
        }
        for (int i = 0; i < confirmaSenha.length; i++) {
            confirmSenhaCompleta += confirmaSenha[i];
        }

        if (!txtRegLogin.getText().trim().isEmpty()
                && !senhaCompleta.trim().isEmpty()
                && !confirmSenhaCompleta.trim().isEmpty()) {
            usuarioExistente = user.verifyUsuarioExistente(txtRegLogin.getText(), conexao);

            if (!usuarioExistente) {
                if (senhaCompleta.equals(confirmSenhaCompleta)) {
                    String[] opcoes = {"Sim", "Não"};
                    String informacoesDigitadas = "As informações digitadas foram: "
                            + "\n\nNome completo: " + txtRegNome.getText()
                            + "\nIdade: " + txtRegIdade.getText()
                            + "\nSexo: " + cmbSexo.getSelectedItem()
                            + "\n\nLogin: " + txtRegLogin.getText()
                            + "\nSenha: " + senhaCompleta
                            + "\n\nEssas informações estão corretas?";
                    int opcaoEsc = JOptionPane.showOptionDialog(this, informacoesDigitadas, "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);

                    switch (opcaoEsc) {
                        case 0:
                            JOptionPane.showMessageDialog(this, "Registrado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);

                            pessoa.insertPessoa(txtRegNome.getText(), Integer.parseInt(txtRegIdade.getText()), "" + cmbSexo.getSelectedItem(), conexao);
                            user.insertUsuario(pessoa.getIdPessoa(txtRegNome.getText(), conexao), txtRegLogin.getText(), senhaCompleta, conexao);

                            login();
                            break;
                        default:
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "As senhas digitadas são diferentes!", "Senhas inválidas!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Esse login já existe!", "Senhas inválidas!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Um ou mais campos estão em branco!", "Campos em branco!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        char[] senha = pwdSenhaLogin.getPassword();

        boolean usuarioExiste = false;
        String senhaCompleta = "";
        int indiceUser = -1;

        for (int i = 0; i < senha.length; i++) {
            senhaCompleta += senha[i];
        }

        if (!txtLogin.getText().trim().isEmpty() && !senhaCompleta.trim().isEmpty()) {
            usuarioExiste = user.verifyUsuarioExistente(txtLogin.getText(), conexao);

            if (usuarioExiste) {
                try {
                    ResultSet getUser = user.getUser(txtLogin.getText(), conexao);
                    getUser.next();
                    if (senhaCompleta.equals(getUser.getString("SENHA"))) {
                        JOptionPane.showMessageDialog(this, "Logado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                        usuarioLogado = txtLogin.getText();
                        lblUserLogado.setText(pessoa.getNomePessoa(user.getIdPessoaByLogin(usuarioLogado, conexao), conexao));
                        atualizaListaCompromissos();
                        compromissos();

                    } else {
                        JOptionPane.showMessageDialog(this, "Senha incorreta!", "Senhas inválida!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro " + e.getSQLState() + "!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado!", "Usuário inválido!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Um ou mais campos estão em branco!", "Campos em branco!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void pwdSenhaLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdSenhaLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_pwdSenhaLoginKeyPressed

    private void pwdRegConfirmSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdRegConfirmSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnRegistrarActionPerformed(null);
        }
    }//GEN-LAST:event_pwdRegConfirmSenhaKeyPressed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        login();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!txtLocal.getText().trim().isEmpty()
                && !txtTitulo.getText().trim().isEmpty()
                && !txtData.getText().trim().isEmpty()) {
            if (txtData.getText().length() == 10) {
                comps.insertCompromisso(user.getIdPessoaByLogin(usuarioLogado, conexao), txtTitulo.getText(), txtLocal.getText(), txtData.getText(), conexao);
                atualizaListaCompromissos();
            } else {
                JOptionPane.showMessageDialog(null, "Data inválida! \nFormato: 01/02/2000", "Data inválida", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Um ou mais campos estão em branco!", "Campos em branco!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        lblUserLogado.setText("");
        modeloTabela.setNumRows(0);
        tabelaIniciada = false;
        login();
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void txtLocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSalvarActionPerformed(null);
        }
    }//GEN-LAST:event_txtLocalKeyPressed

    public void atualizaListaCompromissos() {
        try {
            ResultSet compromissos = comps.getListCompromissos(user.getIdPessoaByLogin(usuarioLogado, conexao), conexao);

            if (!tabelaIniciada) {
                modeloTabela = (DefaultTableModel) tblCompromissos.getModel();
                while (compromissos.next()) {
                    Object[] ob = {compromissos.getInt("ID"), compromissos.getString("TITULO"), compromissos.getString("DATA"), compromissos.getString("LOCAL_COMPROMISSO")};
                    modeloTabela.addRow(ob);

                    tblCompromissos.getColumnModel().getColumn(0).setMaxWidth(25);
                    tblCompromissos.getColumnModel().getColumn(1).setMaxWidth(120);
                    tblCompromissos.getColumnModel().getColumn(2).setMaxWidth(75);
                    tblCompromissos.getColumnModel().getColumn(3).setMaxWidth(120);
                }
                tabelaIniciada = true;
            } else {
                Object[] ob = new Object[4];

                while (compromissos.next()) {
                    ob[0] = compromissos.getInt("ID");
                    ob[1] = compromissos.getString("TITULO");
                    ob[2] = compromissos.getString("DATA");
                    ob[3] = compromissos.getString("LOCAL_COMPROMISSO");
                    
                    tblCompromissos.getColumnModel().getColumn(0).setMaxWidth(25);
                    tblCompromissos.getColumnModel().getColumn(1).setMaxWidth(120);
                    tblCompromissos.getColumnModel().getColumn(2).setMaxWidth(75);
                    tblCompromissos.getColumnModel().getColumn(3).setMaxWidth(120);
                }
                modeloTabela.addRow(ob);
            }
            limparCampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro " + e.getSQLState() + "!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparCampos() {
        txtData.setText("");
        txtLocal.setText("");
        txtLogin.setText("");
        txtRegLogin.setText("");
        txtTitulo.setText("");
        pwdRegConfirmSenha.setText("");
        pwdRegSenha.setText("");
        pwdSenhaLogin.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarSe;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCompromissos;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblLoginInfo;
    private javax.swing.JLabel lblRegConfirmSenha;
    private javax.swing.JLabel lblRegLogin;
    private javax.swing.JLabel lblRegSenha;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserLogado;
    private javax.swing.JPanel pnlCompromissos;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPasswordField pwdRegConfirmSenha;
    private javax.swing.JPasswordField pwdRegSenha;
    private javax.swing.JPasswordField pwdSenhaLogin;
    private javax.swing.JTable tblCompromissos;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtRegIdade;
    private javax.swing.JTextField txtRegLogin;
    private javax.swing.JTextField txtRegNome;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
