/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.escola.inserirNota;

import br.com.escola.beans.Aluno;
import com.sun.glass.events.KeyEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Matheus
 */
public class InserirNotas extends javax.swing.JFrame {

    public ArrayList<Aluno> listaAlunos = new ArrayList<Aluno>();
    public String CONST_TURMA = "JAVA / ANGULAR";
    public int indiceAlunoSelecionado = -1;

    /**
     * Creates new form NewJFrame
     */
    public InserirNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNota = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        btnLimparCampos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAlunos = new javax.swing.JList<>();
        btnExcluirRegistro = new javax.swing.JButton();
        btnLimparTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNotaKeyPressed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNome.setText("Nota:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Inserir Nota");

        btnInserir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnInserir.setText("Salvar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        btnInserir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInserirKeyPressed(evt);
            }
        });

        lblAluno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAluno.setText("Aluno: ");

        txtNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeAlunoKeyPressed(evt);
            }
        });

        lblMateria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMateria.setText("Matéria:");

        txtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMateriaKeyPressed(evt);
            }
        });

        btnLimparCampos.setForeground(new java.awt.Color(255, 0, 0));
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        listAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAlunosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listAlunos);

        btnExcluirRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExcluirRegistro.setForeground(new java.awt.Color(255, 0, 0));
        btnExcluirRegistro.setText("Excluir Registo");
        btnExcluirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRegistroActionPerformed(evt);
            }
        });

        btnLimparTudo.setBackground(new java.awt.Color(255, 0, 0));
        btnLimparTudo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimparTudo.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparTudo.setText("Limpar tudo");
        btnLimparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMateria)
                            .addComponent(lblAluno)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimparCampos))
                            .addComponent(txtMateria)
                            .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInserir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluirRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAluno)
                            .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMateria)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimparCampos)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimparTudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
            if (!txtNomeAluno.getText().trim().isEmpty() && !txtNota.getText().trim().isEmpty() && !txtMateria.getText().trim().isEmpty()) {
                if (Double.parseDouble(txtNota.getText()) >= 0 && Double.parseDouble(txtNota.getText()) <= 10) {

                    if (indiceAlunoSelecionado > -1) {
                        getAluno(indiceAlunoSelecionado).setNome(txtNomeAluno.getText());
                        getAluno(indiceAlunoSelecionado).setMateria(txtMateria.getText());
                        getAluno(indiceAlunoSelecionado).setNota(Double.parseDouble(txtNota.getText()));
                        indiceAlunoSelecionado = -1;
                    } else {
                        Aluno aluno = new Aluno(txtNomeAluno.getText(), CONST_TURMA, txtMateria.getText(), Double.parseDouble(txtNota.getText()));

                        listaAlunos.add(aluno);
                    }
                    atualizaLista();
                } else {
                    JOptionPane.showMessageDialog(this, "A Nota digitada é Maior/Menor que o permitido", "Nota inválida!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Um ou mais campos estão vazios \nPreencha todos por favor!", "Campos em branco", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro! " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        if(listAlunos.getSelectedIndex() > -1) {
            listAlunos.clearSelection();
        }
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnLimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTudoActionPerformed
        String[] limpo = {""};

        indiceAlunoSelecionado = -1;
        listAlunos.setListData(limpo);
        listaAlunos.removeAll(listaAlunos);
    }//GEN-LAST:event_btnLimparTudoActionPerformed

    private void btnExcluirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRegistroActionPerformed
        if (listAlunos.getSelectedIndex() > -1) {
            int indiceSelecionado = listAlunos.getSelectedIndex();
            listaAlunos.remove(indiceSelecionado);
            atualizaLista();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Registro!", "Registro não selecionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirRegistroActionPerformed

    private void txtNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnInserirActionPerformed(null);
            txtNomeAluno.requestFocus();
        }
    }//GEN-LAST:event_txtNotaKeyPressed

    private void txtNomeAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAlunoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtMateria.requestFocus();
        }
    }//GEN-LAST:event_txtNomeAlunoKeyPressed

    private void txtMateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNota.requestFocus();
        }
    }//GEN-LAST:event_txtMateriaKeyPressed

    private void btnInserirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInserirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnInserirActionPerformed(null);
            txtNota.requestFocus();
        }
    }//GEN-LAST:event_btnInserirKeyPressed

    private void listAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAlunosMouseClicked
        indiceAlunoSelecionado = listAlunos.getSelectedIndex();
        Aluno alunoSelecionado = getAluno(indiceAlunoSelecionado);

        txtNomeAluno.setText(alunoSelecionado.getNome());
        txtMateria.setText(alunoSelecionado.getMateria());
        txtNota.setText("" + alunoSelecionado.getNota());
    }//GEN-LAST:event_listAlunosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirNotas().setVisible(true);
            }
        });
    }

    public void atualizaLista() {
        String[] listaAlunosString = new String[listaAlunos.size()];

        for (int i = 0; i < listaAlunos.size(); i++) {
            listaAlunosString[i] = "[" + (i + 1) + "] " + getAluno(i).getNome();
            listaAlunosString[i] += " - " + getAluno(i).getMateria();
            listaAlunosString[i] += " : " + getAluno(i).getNota();
        }

        listAlunos.setListData(listaAlunosString);
        limparCampos();
    }

    public Aluno getAluno(int indice) {
        return listaAlunos.get(indice);
    }

    public void limparCampos() {
        txtMateria.setText("");
        txtNota.setText("");
        txtNomeAluno.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirRegistro;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnLimparTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNome;
    private javax.swing.JList<String> listAlunos;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables

}
